# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Node.js image as the base
FROM node:22.12-alpine AS builder

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package.json package-lock.json ./

# Copy the source files needed for build
COPY src ./src
COPY tsconfig.json ./

# Install dependencies (this will also run the prepare script)
RUN --mount=type=cache,target=/root/.npm npm install

# Build the application
RUN npm run build

# Use a lightweight Node.js image for the final build
FROM node:22-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the build output and node_modules from the builder stage
COPY --from=builder /app/build ./build
COPY --from=builder /app/node_modules ./node_modules

# Don't set default environment variables to ensure proper tool discovery
# These should be provided at runtime

# Expose HTTP port
EXPOSE 3000

# Set default PORT environment variable
ENV PORT=3000

# Specify the command to run the HTTP server
ENTRYPOINT ["node", "build/http-server.js"]